theme: jekyll-theme-midnight
title: Vasilije Kovačević
description: a Game Designer from Montenegro
font: '"Rubik", "Helvetica Neue", sans-serif'
load_google_fonts: 'Rubik:400,400italic,700,700italic'